# Generated by Django 5.1.7 on 2025-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0003_order_orderitem_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default='Paid', max_length=20),
        ),
    ]
