# Generated by Django 5.1.7 on 2025-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0004_alter_payment_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Completed', max_length=20),
        ),
    ]
