# Generated by Django 5.1.7 on 2025-08-13 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_housefeature'),
        ('houseprojectapp', '0005_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('cent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('squarefeet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('time_duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('additional_features', models.ManyToManyField(blank=True, to='adminapp.housefeature')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='adminapp.category')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='houseprojectapp.tbl_engineer')),
            ],
        ),
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='work_proofs/')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='houseprojectapp.work')),
            ],
        ),
    ]
