# Generated by Django 5.1.7 on 2025-08-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0006_work_workimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='property_image',
            field=models.ImageField(blank=True, null=True, upload_to='property_images/'),
        ),
    ]
