# Generated by Django 5.1.7 on 2025-08-19 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0007_work_property_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('suggestion', models.FileField(blank=True, null=True, upload_to='suggestions/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='houseprojectapp.tbl_engineer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_requests', to='houseprojectapp.tbl_register')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_requests', to='houseprojectapp.userrequest')),
            ],
        ),
    ]
