# Generated by Django 5.1.7 on 2025-08-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0008_engineerrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='additional_features',
        ),
        migrations.AddField(
            model_name='work',
            name='additional_features',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
