# Generated by Django 5.1.7 on 2025-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0009_remove_work_additional_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='cent',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
