# Generated by Django 5.1.7 on 2025-08-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0010_alter_userrequest_cent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='cent',
            field=models.FloatField(),
        ),
    ]
