# Generated by Django 5.1.7 on 2025-10-21 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0011_alter_userrequest_cent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('suggestion', models.FileField(blank=True, null=True, upload_to='engineer_suggestions/')),
                ('cent', models.CharField(blank=True, max_length=50, null=True)),
                ('sqft', models.CharField(blank=True, max_length=50, null=True)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='houseprojectapp.tbl_engineer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineer_bookings', to='houseprojectapp.tbl_register')),
                ('user_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='houseprojectapp.userrequest')),
            ],
        ),
    ]
