# Generated by Django 5.1.7 on 2025-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0012_engineerbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerbooking',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
