# Generated by Django 5.1.7 on 2025-10-23 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0013_engineerbooking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseprojectapp.tbl_engineer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseprojectapp.tbl_register')),
            ],
        ),
    ]
