# Generated by Django 5.1.7 on 2025-10-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_housefeature"),
        ("houseprojectapp", "0014_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineerbooking",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="bookings", to="adminapp.housefeature"
            ),
        ),
    ]
