# Generated by Django 5.1.7 on 2025-11-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0017_alter_cart_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartcheckout",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(default="success", max_length=100),
        ),
    ]
