# Generated by Django 5.1.7 on 2025-11-11 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0018_cartcheckout_total_amount_alter_cart_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkout",
            name="total_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
