# Generated by Django 5.1.7 on 2025-11-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0019_checkout_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartcheckout",
            name="total_amount",
        ),
        migrations.RemoveField(
            model_name="checkout",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="cartcheckout",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="checkout",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productbookings",
            name="total_price",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
