# Generated by Django 5.1.7 on 2025-11-11 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0020_remove_cartcheckout_total_amount_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartcheckout",
            old_name="total_price",
            new_name="total_amount",
        ),
        migrations.RenameField(
            model_name="checkout",
            old_name="total_price",
            new_name="total_amount",
        ),
    ]
