# Generated by Django 5.1.7 on 2025-11-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "houseprojectapp",
            "0021_rename_total_price_cartcheckout_total_amount_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(default="pending", max_length=100),
        ),
    ]
