# Generated by Django 5.1.7 on 2025-11-12 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0022_alter_cart_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartcheckout",
            name="booking",
        ),
        migrations.RemoveField(
            model_name="cartcheckout",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cartupi",
            name="user",
        ),
        migrations.CreateModel(
            name="CartPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cart_ids", models.JSONField(default=list)),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("card", "Card"), ("upi", "UPI")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("upi_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "card_holder_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("card_number", models.CharField(blank=True, max_length=16, null=True)),
                ("expiry_date", models.CharField(blank=True, max_length=7, null=True)),
                ("cvv", models.CharField(blank=True, max_length=4, null=True)),
                ("total_amount", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="houseprojectapp.tbl_register",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="CartCard",
        ),
        migrations.DeleteModel(
            name="CartCheckout",
        ),
        migrations.DeleteModel(
            name="CartUpi",
        ),
    ]
