# Generated by Django 5.1.7 on 2025-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "houseprojectapp",
            "0023_remove_cartcheckout_booking_remove_cartcheckout_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartpayment",
            name="payment_type",
            field=models.CharField(
                choices=[("card", "Card"), ("upi", "UPI"), ("cod", "Cash on Delivery")],
                max_length=10,
            ),
        ),
    ]
