# Generated by Django 5.1.7 on 2025-11-14 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "houseprojectapp",
            "0025_remove_checkout_booking_remove_checkout_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cartpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="completed",
                max_length=10,
            ),
        ),
    ]
