# Generated by Django 5.1.7 on 2025-11-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "houseprojectapp",
            "0026_alter_bookingpayment_status_alter_cartpayment_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("upi", "UPI"),
                    ("card", "Card"),
                    ("cash", "Cash on Delivery"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="cartpayment",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("card", "Card"),
                    ("upi", "UPI"),
                    ("cash", "Cash on Delivery"),
                ],
                max_length=10,
            ),
        ),
    ]
