# Generated by Django 5.1.7 on 2025-11-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0027_alter_bookingpayment_payment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookingpayment",
            name="payment_choice",
            field=models.CharField(default="booking_payment", max_length=20),
        ),
        migrations.AddField(
            model_name="cartpayment",
            name="payment_choice",
            field=models.CharField(default="cart_payment", max_length=20),
        ),
        migrations.AlterField(
            model_name="productbookings",
            name="status",
            field=models.CharField(default="completed", max_length=100),
        ),
    ]
