# Generated by Django 5.1.7 on 2025-11-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0028_bookingpayment_payment_choice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engineerbooking",
            name="reject_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
