# Generated by Django 5.1.7 on 2025-11-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houseprojectapp", "0029_engineerbooking_reject_reason"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EngineerRequest",
        ),
    ]
