# Generated by Django 6.0.1 on 2026-01-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0030_delete_engineerrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerbooking',
            name='advance_booking',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
