# Generated by Django 6.0.1 on 2026-01-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houseprojectapp', '0031_engineerbooking_advance_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineerBookingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('cash', 'Cash on Delivery')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=10)),
                ('card_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=16, null=True)),
                ('expiry_date', models.CharField(blank=True, max_length=7, null=True)),
                ('cvv', models.CharField(blank=True, max_length=4, null=True)),
                ('total_amount', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='houseprojectapp.engineerbooking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houseprojectapp.tbl_register')),
            ],
        ),
    ]
