# Generated by Django 5.1.7 on 2025-07-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='expected_amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
