# Generated by Django 5.1.7 on 2025-08-11 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_categoryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
