# Generated by Django 5.1.7 on 2025-08-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_categoryimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
