# Generated by Django 5.1.7 on 2025-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_categoryimage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
