# Generated by Django 5.1.7 on 2025-11-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_housefeature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product_tbl",
            name="category",
        ),
        migrations.DeleteModel(
            name="Product_table",
        ),
        migrations.DeleteModel(
            name="Product_tbl",
        ),
    ]
