# Generated by Django 5.1.7 on 2025-11-16 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0008_remove_product_tbl_category_delete_product_table_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="category",
        ),
        migrations.RemoveField(
            model_name="houseimage",
            name="house",
        ),
        migrations.DeleteModel(
            name="CategoryImage",
        ),
        migrations.DeleteModel(
            name="House",
        ),
        migrations.DeleteModel(
            name="HouseImage",
        ),
    ]
